model:
  - name: batch_size
    value: 64
  - name: sequence_length
    value: 128
  - name: d_model
    value: 32
  - name: n_layers
    value: 4
  - name: n_heads
    value: 4

training:
  - name: learning_rate
    value: 0.0003
  - name: num_epochs
    value: 100
  - name: eval_iters
    value: 20
  
